import type { DeclaredRoute } from './declared-routes.js'
import type { RouteRule } from '../services/redis-rbac.repository.js'

/**
 * jinbe's route_map, GENERATED from its declarations alone (authz-v2-design §3.1): `npm run
 * gen:route-map` writes route-map.generated.ts and CI fails when the file and the running route table
 * disagree. No hand rows, no aliases, no catch-all but the documentation:
 *
 *   permission P                    {method, path, permission: P} (+ org_param), one more per alsoAccepts
 *   scoped by its own guard (audit) {method, path} — any signed-in person; the guard narrows
 *   access self | authenticated     {method, path}
 *   access public                   {method, path, public: true}
 *   access machine, edge            {method, path, public: true} (SCIM authenticates itself)
 *   access machine                  no row: the gateway answers not_found (OPAL feeds, rules, webhooks)
 *   /docs*                          DOCS_ROW, added by the bootstrap only with ENABLE_SWAGGER
 */

export const DOCS_ROW: RouteRule = { method: 'GET', path: '/docs/:any*', public: true }

const isDocs = (path: string) => /^\/docs(\/|$)/.test(path)

export function routeMapRows(declared: readonly DeclaredRoute[]): RouteRule[] {
  const rows: RouteRule[] = []
  const seen = new Set<string>()
  const push = (row: RouteRule) => {
    const key = `${row.method} ${row.path} ${row.permission ?? ''}`
    if (seen.has(key)) return
    seen.add(key)
    rows.push(row)
  }
  const sorted = [...declared]
    .filter((r) => r.method !== 'HEAD' && !isDocs(r.path))
    .sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))
  for (const r of sorted) {
    const base = { method: r.method, path: r.path }
    if (r.permission) {
      if (r.scopedBy) {
        push(base)
        continue
      }
      const org = r.org ? { org_param: r.org } : {}
      for (const permission of [r.permission, ...(r.alsoAccepts ?? [])]) push({ ...base, permission, ...org })
      continue
    }
    switch (r.access) {
      case 'self':
      case 'authenticated':
        push(base)
        break
      case 'public':
        push({ ...base, public: true })
        break
      case 'machine':
        if (r.edge) push({ ...base, public: true })
        break
      default:
        // `authenticated` class with no access recorded (read off guards): any signed-in person.
        if (r.class === 'authenticated') push(base)
    }
  }
  return rows
}

/** The generated file's contents (scripts/gen-route-map.ts writes it; the CI test compares it). */
export function renderRouteMapModule(rows: readonly RouteRule[]): string {
  return [
    '// GENERATED by `npm run gen:route-map` from the routes jinbe declares (policy/route-map.ts).',
    "// Do not edit: change the route's declaration or the catalogue, then regenerate.",
    "import type { RouteRule } from '../services/redis-rbac.repository.js'",
    '',
    'export const GENERATED_ROUTE_MAP: readonly RouteRule[] = [',
    ...rows.map((r) => `  ${JSON.stringify(r)},`),
    ']',
    '',
  ].join('\n')
}
